/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UebaRouteImport } from './routes/ueba'
import { Route as ThreatAnalyticsRouteImport } from './routes/threat-analytics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LiveLogsRouteImport } from './routes/live-logs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IncidentResponseRouteImport } from './routes/incident-response'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const UebaRoute = UebaRouteImport.update({
  id: '/ueba',
  path: '/ueba',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatAnalyticsRoute = ThreatAnalyticsRouteImport.update({
  id: '/threat-analytics',
  path: '/threat-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLogsRoute = LiveLogsRouteImport.update({
  id: '/live-logs',
  path: '/live-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentResponseRoute = IncidentResponseRouteImport.update({
  id: '/incident-response',
  path: '/incident-response',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/incident-response': typeof IncidentResponseRoute
  '/integrations': typeof IntegrationsRoute
  '/live-logs': typeof LiveLogsRoute
  '/settings': typeof SettingsRoute
  '/threat-analytics': typeof ThreatAnalyticsRoute
  '/ueba': typeof UebaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/incident-response': typeof IncidentResponseRoute
  '/integrations': typeof IntegrationsRoute
  '/live-logs': typeof LiveLogsRoute
  '/settings': typeof SettingsRoute
  '/threat-analytics': typeof ThreatAnalyticsRoute
  '/ueba': typeof UebaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/geo': typeof GeoRoute
  '/incident-response': typeof IncidentResponseRoute
  '/integrations': typeof IntegrationsRoute
  '/live-logs': typeof LiveLogsRoute
  '/settings': typeof SettingsRoute
  '/threat-analytics': typeof ThreatAnalyticsRoute
  '/ueba': typeof UebaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/geo'
    | '/incident-response'
    | '/integrations'
    | '/live-logs'
    | '/settings'
    | '/threat-analytics'
    | '/ueba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/geo'
    | '/incident-response'
    | '/integrations'
    | '/live-logs'
    | '/settings'
    | '/threat-analytics'
    | '/ueba'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/geo'
    | '/incident-response'
    | '/integrations'
    | '/live-logs'
    | '/settings'
    | '/threat-analytics'
    | '/ueba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  GeoRoute: typeof GeoRoute
  IncidentResponseRoute: typeof IncidentResponseRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LiveLogsRoute: typeof LiveLogsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatAnalyticsRoute: typeof ThreatAnalyticsRoute
  UebaRoute: typeof UebaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueba': {
      id: '/ueba'
      path: '/ueba'
      fullPath: '/ueba'
      preLoaderRoute: typeof UebaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-analytics': {
      id: '/threat-analytics'
      path: '/threat-analytics'
      fullPath: '/threat-analytics'
      preLoaderRoute: typeof ThreatAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-logs': {
      id: '/live-logs'
      path: '/live-logs'
      fullPath: '/live-logs'
      preLoaderRoute: typeof LiveLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident-response': {
      id: '/incident-response'
      path: '/incident-response'
      fullPath: '/incident-response'
      preLoaderRoute: typeof IncidentResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  GeoRoute: GeoRoute,
  IncidentResponseRoute: IncidentResponseRoute,
  IntegrationsRoute: IntegrationsRoute,
  LiveLogsRoute: LiveLogsRoute,
  SettingsRoute: SettingsRoute,
  ThreatAnalyticsRoute: ThreatAnalyticsRoute,
  UebaRoute: UebaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
