import os
import jwt
import base64
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv

load_dotenv()

security = HTTPBearer()

SUPABASE_JWT_SECRET = os.getenv("SUPABASE_JWT_SECRET")

def verify_supabase_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """
    Verify the JWT token generated by Supabase using the project's JWT Secret.
    """
    if not SUPABASE_JWT_SECRET:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="SUPABASE_JWT_SECRET is not set in the environment variables."
        )

    token = credentials.credentials
    try:
        # Decode the secret if it's base64 encoded
        try:
            secret = SUPABASE_JWT_SECRET
            if "==" in secret or secret.endswith("="):
                 secret = base64.b64decode(SUPABASE_JWT_SECRET)
        except:
            secret = SUPABASE_JWT_SECRET

        payload = jwt.decode(
            token,
            secret,
            algorithms=["HS256"],
            audience="authenticated"
        )
        return payload
    except Exception as local_err:
        # Fallback to Supabase Auth API if local verification fails
        try:
            from app.db.supabase_client import get_supabase
            supabase = get_supabase()
            res = supabase.auth.get_user(token)
            if res and res.user:
                return {"sub": res.user.id, "email": res.user.email}
        except Exception as api_err:
            pass
            
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid token. Local: {str(local_err)}",
            headers={"WWW-Authenticate": "Bearer"},
        )
